org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


## Mod Properties
modId=simpletoolbelt
modName=Simple Toolbelt
modLicense=MIT
modGroupId=net.scratch221171.simpletoolbelt
modAuthors=scratch221171
modDescription=
modDisplayUrl=https://github.com/scratch221171/SimpleToolbelt
modIssueTrackerUrl=https://github.com/scratch221171/SimpleToolbelt/issues
modCredits=


## Fabric Mod Properties
modFabricEnvironment=*
modFabricEntrypoint=net.scratch221171.simpletoolbelt.SimpleToolbelt
modFabricClientEntrypoint=net.scratch221171.simpletoolbelt.client.SimpleToolbeltClient
